removing JSON and index.csv from the lib

diff --git a/mondrian b/mondrian
--- a/mondrian
+++ b/mondrian
@@ -3,9 +3,7 @@ workdir=/home/gavin/Pictures/artWork/recurrences
 
 # use randmoness to automatically select a model for recurrink to process
 rndmodel() {
-  model_path=$(ls -1d ${workdir}/*| sort -R| tail -1)
-  model=${model_path%.*}  # retain the part before the colon
-  model=${model##*/}  # retain the part after the last slash
+  model=$(./recurrink.py --random)
   echo $model
 }
 
@@ -57,6 +55,21 @@ mkjson() {
 }
 
 mksvg() {
+  pid=/tmp/rink.pid
+  if [[ -L "${pid}" ]]
+  then 
+    model=`readlink $pid | awk -v FS='/' '{print $7}'`
+    view=`readlink $pid | awk -v FS='/' '{print $9}'`
+    view="${view/.json/}"
+    # echo "/tmp/${model}.rink"
+    ./recurrink.py -m ${model} --output RINK --view ${view}
+  else
+    echo "error: $0 -i needs ${pid}"
+    exit 1
+  fi
+}
+
+updsvg() {
   # echo "mksvg" $m
   model=$m
   cells=$(./recurrink.py -m ${model} --output CELL)
@@ -95,11 +108,6 @@ mkinstall() {
   then 
     model=`readlink $pid | awk -v FS='/' '{print $7}'`
     # echo $model
-    if [ -f "/tmp/${model}.json" ]
-    then
-      echo ${dbentry}
-      mv "/tmp/${model}.json" ${dbentry}
-    fi
     if [ -f "/tmp/${model}.svg" ]
     then
       svgname="${dbentry/json/svg}"
@@ -113,7 +121,7 @@ mkinstall() {
   fi
 }
 
-n=0; f=0; c=0; j=0; s=0; i=0
+n=0; f=0; c=0; j=0; s=0; u=0; i=0
 
 usage() { 
   echo "Usage: $0
@@ -122,11 +130,12 @@ usage() {
 	-c -m MODEL -a AUTH	make csv
 	-j -m MODEL -a AUTH	make json
 	-s -m MODEL        	make svg
-	-i 			install json, svg to library
+	-u -m MODEL        	update svg
+	-i 			install svg in pubq
 " 1>&2; exit 1; 
 }
 
-while getopts "nfcjsim:a:" o; do
+while getopts "nfcjsuim:a:" o; do
   case "${o}" in
     a)
       a=${OPTARG}
@@ -148,6 +157,9 @@ while getopts "nfcjsim:a:" o; do
       ;;
     s)
       s=1
+      ;;
+    u)
+      u=1
       ;;
     i)
       i=1
@@ -174,6 +186,9 @@ then
 elif [ "${s}" -eq 1 ] && [ -n "${m}" ]
 then
   mksvg
+elif [ "${u}" -eq 1 ] && [ -n "${m}" ]
+then
+  updsvg
 elif [ "${i}" -eq 1 ]
 then
   mkinstall
