mondrian rewritten

diff --git a/mondrian b/mondrian
--- a/mondrian
+++ b/mondrian
@@ -1,26 +1,19 @@
 #!/bin/bash
-
-# opt 1 model=M has no value RETURN model
-# opt 2 model=M RETURN nothing for success or error
-# opt 3 model=M RETURN digest 
-
 workdir=/home/gavin/Pictures/artWork/recurrences
-s=0
 
 # use randmoness to automatically select a model for recurrink to process
-get_random_model() {
+rndmodel() {
   model_path=$(ls -1d ${workdir}/*| sort -R| tail -1)
   model=${model_path%.*}  # retain the part before the colon
   model=${model##*/}  # retain the part after the last slash
+  echo $model
 }
 
-get_cells() {
-  cells=$(./recurrink.py -m ${model} --output CSV --random)
-  if [ -z "${cells}" ]
-  then
-    echo "cannot find cells for ${model}"
-    exit 1
-  fi
+rndfactor() {
+  # scaling is weighted in favour of 1:1
+  declare -a a=(0.5 0.75 1.0 1.5 2.0)
+  i=$((0 + $RANDOM % 5))
+  echo ${a[$i]}
 }
 
 update_svg() {
@@ -51,27 +44,146 @@ update_svg() {
      --top ${top} /tmp/${model}.svg
   done
 }
-usage() { 
-  echo "Usage: $0 [-n new model ] [ -s scale ] [-m <model> -d get digest ] [ -m <model> -r make rink ] " 1>&2; exit 1; 
+
+mkcsv() {
+  # echo "mkcsv" $m $a
+  model=$m
+  if [ "$a" == 'machine' ]
+  then
+    cells=$(./recurrink.py -m ${model} --output CSV --random)
+  elif [ "$a" == 'human' ]
+  then
+    cells=$(./recurrink.py -m ${model} --output CSV)
+  else
+    usage
+  fi
+
+  if [ -z "${cells}" ]  # although cells are thrown away, they signify success
+  then
+    echo "error: cannot find cells"
+    exit 1
+  else
+    echo ${cells}
+  fi
 }
 
-while getopts "m:nsd:r:" o; do
+mkjson() {
+  # echo "mkjson" $m $a
+  # symlink is a promise that will be fulfilled when /tmp/MODEL.json is approved
+  model=$m
+  if [ "$a" == 'machine' ]
+  then
+    digest=$(./recurrink.py -m ${model} --output JSON --random)
+    ln -s "$workdir/$model/m/$digest.json" /tmp/rink.pid
+  elif [ "$a" == 'human' ]
+  then
+    digest=$(./recurrink.py -m ${model} --output JSON)
+    ln -s "$workdir/$model/h/$digest.json" /tmp/rink.pid 
+  else
+    usage
+  fi
+  echo $digest
+}
+
+mksvg() {
+  # echo "mksvg" $m
+  model=$m
+  cells=$(./recurrink.py -m ${model} --output CELL)
+
+  for cell in ${cells}
+  do
+    attrs=$(./recurrink.py -m ${model} --cell ${cell})
+    a=($attrs)  # convert to array with the magic of IFS separator
+    shape=${a[2]} # elems 0,1 are cell and model names
+    size=${a[3]}
+    facing=${a[4]}
+    bgcol=${a[6]}
+    width=${a[9]}
+    top=${a[12]}
+    echo -n "${cell} ${shape}" 
+    # update cells
+    # echo "c ${cell},m ${model},s ${shape},w ${width},f ${facing},z ${size},b ${bgcol},t ${top}"
+    # 0 1        2      3      4    5    6               7   8    9 0 1   2
+    # a soleares circle medium west #fff mediumvioletred 1.0 #000 0 0 1.0 True
+    # d,soleares,circle,1.0,south,large,white,False
+  ./effect.py \
+     --id ${cell}1 \
+     --output /tmp/${model}.svg \
+     --shape ${shape} \
+     --width ${width} \
+     --facing ${facing} \
+     --size ${size} \
+     --bg ${bgcol} \
+     --top ${top} /tmp/${model}.svg
+  done
+}
+
+mkinstall() {
+
+  pid=/tmp/rink.pid
+  dbentry=`readlink $pid`
+  pubdir=/home/gavin/Pictures/pubq
+
+  if [[ -L "${pid}" ]]
+  then 
+    model=`readlink $pid | awk -v FS='/' '{print $7}'`
+    # echo $model
+    if [ -f "/tmp/${model}.json" ]
+    then
+      echo ${dbentry}
+      mv "/tmp/${model}.json" ${dbentry}
+    fi
+    if [ -f "/tmp/${model}.svg" ]
+    then
+      svgname="${dbentry/json/svg}"
+      echo ${svgname}
+      mv "/tmp/${model}.svg" ${svgname}
+      ln -s ${svgname} ${pubdir}
+    fi
+  else
+    echo "error: $0 -i needs ${pid}"
+    exit 1
+  fi
+}
+
+n=0; f=0; c=0; j=0; s=0; i=0
+
+usage() { 
+  echo "Usage: $0
+	-n 			get random model name
+	-f 			get random factor
+	-c -m MODEL -a AUTH	make csv
+	-j -m MODEL -a AUTH	make json
+	-s -m MODEL        	make svg
+	-i 			install json, svg to library
+" 1>&2; exit 1; 
+}
+
+while getopts "nfcjsim:a:" o; do
   case "${o}" in
-    d)
-      d=${OPTARG}
-      ;;
-    r)
-      r=${OPTARG}
+    a)
+      a=${OPTARG}
       ;;
     m)
       m=${OPTARG}
       ;;
     n)
-      get_random_model
-      n=${model}
+      n=1
+      ;;
+    f)
+      f=1
+      ;;
+    c)
+      c=1
+      ;;
+    j)
+      j=1
       ;;
     s)
       s=1
+      ;;
+    i)
+      i=1
       ;;
     *)
       usage
@@ -80,43 +192,24 @@ while getopts "m:nsd:r:" o; do
 done
 shift $((OPTIND-1))
 
-if [ -z "${n}" ] && [ -z "${m}" ] && [ -z "${s}" ]; then
-    usage
-fi
-
-if [ -n "${n}" ]; then
-  echo ${n}
-elif [ "${s}" -eq 1 ]; then
-  # scaling is weighted in favour of 1:1
-  declare -a a=(1.0 0.5 1.0 2.0 1.0)
-  i=$((0 + $RANDOM % 5))
-  echo ${a[$i]}
-elif [ -n "${m}" ] && [ "${d}" == 'none' ]; then
-  model=$m
-  get_cells
-  echo ${cells}
-elif [ -n "${m}" ] && [ -n "${d}" ]; then
-  model=$m
-  if [ ! -f "/tmp/${model}.svg" ]
-  then
-    echo "File '$model.svg' not found in /tmp"
-    exit 1
-  else
-    update_svg
-    /bin/mv /tmp/${model}.svg ${d}.svg
-    echo ${digest}
-  fi
-elif [ -n "${m}" ] && [ "${r}" == 'none' ]; then
-  model=$m
-  digest=$(./recurrink.py -m ${model} --output JSON --random)
-  /bin/mv /tmp/${digest}.json ${workdir}/${model}/m
-  echo $digest
-  ./recurrink.py --view ${digest} --output RINK
-  ./input.py --output ${digest}.svg /tmp/${model}.rink
-elif [ -n "${m}" ] && [ -n "${r}" ]; then
-  echo $r
-  model=$m
-  ./recurrink.py -m ${model} --output RINK --view $r
+if [ "${n}" -eq 1 ]
+then
+  rndmodel
+elif [ "${f}" -eq 1 ]
+then
+  rndfactor
+elif [ "${c}" -eq 1 ] && [ -n "${m}" ] && [ -n "${a}" ]
+then
+  mkcsv
+elif [ "${j}" -eq 1 ] && [ -n "${m}" ] && [ -n "${a}" ]
+then
+  mkjson
+elif [ "${s}" -eq 1 ] && [ -n "${m}" ]
+then
+  mksvg
+elif [ "${i}" -eq 1 ]
+then
+  mkinstall
 else
   usage
 fi
